AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Root template which contains nested stacks
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Resources:
  HelloWorldApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./hello-world-template.yaml

  TasksTable:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./dynamodb-template.yaml

